name: Playwright Test

on:
  workflow_call:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Map custom domain to localhost
        run: echo "127.0.0.1 local.k-pullup.com" | sudo tee -a /etc/hosts

      - name: Start dev server
        run: yarn dev &

      - name: Wait for dev server
        run: npx wait-on https://local.k-pullup.com:5173

      - name: Run Playwright tests
        run: yarn playwright test
